export const dataText = {
	TITLE: 'Célula 30',
	SUBTITLE: 'Mais que uma célula, nossa maneira de sermos igreja',
	ERROR: 'Errou a senha',
	ERRORTEXT: 'Experimente entrar como visitante',
	ERRORTEXTTWO: 'e tenha acesso ao que de melhor acontece entre nós',
	ERRORINVITE: 'Seja bem vindo em nome de Jesus',
	WHATISACELL: 'O que é uma célula',
	BYSHEPERD: 'By Pastor Aluízio Silva',
	WORDSSHEPERD: 'Palavras Poderosas dos nossos pastores',
	LASTNEWS: 'Fique atento às nossas novidades',
	MEMBER: 'obrigado por ser membro da nossa célula',
	VISITOR: 'Venha fazer parte da nossa célula',
	VERYIMPORTANT: 'Você é muito importante para nós',
	NAME: 'Nome:',
	BIRTHDATE: 'Nascimento:',
	PHONE: 'Telefone:',
	EMAIL: 'email:',
	FUNCTION: 'Cargo:',
	SINCE: 'Na célula desde:',
	LEADER: 'Quem é o líder da célula? ',
	BIRTHDATECELL: 'Em que ano nasceu essa célula?',
	FIRSTCELLNUMBER: 'Qual o número da nossa primeira célula?',
	CELLLOCATION: 'Onde normalmente fazemos a reunião da célula?',
	DAYCELL: 'Qual é o dia que normalmente fazemos a reunião da célula?',
	LEADERARRIVED: 'Em que ano o nosso líder chegou na igreja?',
	SHEPERDNAME: 'Qual é o nome do nosso pastor de jovens?',
	COMMUNION: 'Qual é a comunhão que mais fazemos?',
	DISCIPLERNAME: 'Qual é o nome do(a) nosso(a) discipulador(a)?',
	HOWMANYMEMBERS: 'Quantos membros da célula são frequentes nos cultos?'
}